### ISSUE TITLE
Column must not be null using oracle jdbc

### ISSUE THREAD

**Issue by msimmons** [msimmons/jdbcode#14]
Getting the following stack trace describing table:
using oracle jdbc

java.lang.IllegalStateException: column must not be null
	at net.contrapt.jdbcode.service.SchemaDescriber.describeTable(SchemaDescriber.kt:138)
	at net.contrapt.jdbcode.service.SchemaDescriber.describeObject(SchemaDescriber.kt:88)
	at net.contrapt.jdbcode.service.ConnectionService.describe(ConnectionService.kt:100)

**Comment by msimmons** [comment]
Fixed by d964bc38bbaf716e36eefc26cd1e2a458bd21230 (hopefully)
