### ISSUE TITLE
Invalid table name using oracle jdbc

### ISSUE THREAD

**Issue by msimmons** [msimmons/jdbcode#15]
Follwing stack trace:

2018-12-11 10:23:14.989 [vert.x-worker-thread-7] ERROR net.contrapt.jdbcode.JDBCVerticle - getting objects
java.sql.SQLSyntaxErrorException: ORA-00903: invalid table name

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:896)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1661)
	at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:1626)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1613)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:282)
	at oracle.jdbc.OracleDatabaseMetaData.getIndexInfo(OracleDatabaseMetaData.java:3756)
	at net.contrapt.jdbcode.service.SchemaDescriber.describeTable(SchemaDescriber.kt:130)
	at net.contrapt.jdbcode.service.SchemaDescriber.describeObject(SchemaDescriber.kt:88)
	at net.contrapt.jdbcode.service.ConnectionService.describe(ConnectionService.kt:100)
	at net.contrapt.jdbcode.JDBCVerticle$start$11$1.handle(JDBCVerticle.kt:216)
	at net.contrapt.jdbcode.JDBCVerticle$start$11$1.handle(JDBCVerticle.kt:15)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by msimmons** [comment]
Various issues retrieving index info in oracle in certain cases -- probably need to wrap in try/catch and just ignore if we can't get it.

**Comment by msimmons** [comment]
Fixed by 91c6cabcca088630474d75f9a3cb402a2c4a66ff
