### ISSUE TITLE
Data type handling

### ISSUE THREAD

**Issue by msimmons** [msimmons/jdbcode#18]
- clobs and blobs (eg oracle) not turned into strings

**Comment by msimmons** [comment]
Fixed by f554747b8b951197e6783a42173a0dac3cde305e

**Comment by msimmons** [comment]
2019-01-22 16:01:31.443 [vert.x-worker-thread-14] WARN  n.c.j.service.StatementExecutor - Exception converting oracle.sql.CLOB@346fe37c (class oracle.sql.CLOB)
java.sql.SQLException: Invalid argument(s) in call
	at oracle.sql.CLOB.getSubString(CLOB.java:276)
	at net.contrapt.jdbcode.service.StatementExecutor.convertValue(StatementExecutor.kt:164)
	at net.contrapt.jdbcode.service.StatementExecutor.fetch(StatementExecutor.kt:78)
	at net.contrapt.jdbcode.service.ConnectionService.execute(ConnectionService.kt:65)
